### PR TITLE
Adaptor support for non-graphql

### PR DESCRIPTION
**Pull request by pcwinters**
@gyzerok, I'm a fan of what you're doing with adrenaline.
I would love to see adrenaline decouple from graphql in order to support arbitrary transport, reducer, and normalization strategies.

### CODE REVIEW

**Comment by pcwinters** [comment]
@gyzerok , please take a look. My example doesn't fully flush out a complex REST server, but it demonstrates how it's possible.

**Comment by gyzerok** [comment]
I guess ```Adaptor``` should be renamed to ```Adapter```. Gonna check it soon.

**Comment by gyzerok** [comment]
@pcwinters Excuse me for being so slow. Rihgt now I'm moving to another city and thats why have not enough time to dig deeper.

For now as I've understood from your code this is an excellent approach! With your ideas we may try to build more general solution on top of Relay idea and Adrenaline.

What do you think about defining a set of projections instead of just arguments inside of `query` on a SmartComponent? Currently we use GraphQL to describe data requirements on the `query`. Correct me if I'm wrong you use `query` to pass parameters to the server. If so, we need to investigate in some general for of passing projections down to the rest server to make things similar to GraphQL approach.

**Comment by gyzerok** [comment]
What I'm talking about is something like this:

```js
export default createSmartComponent(TodoApp, {
  initialVariables: {
    count: 2,
  },
  query: (variables) => ({
     todo: {
       text: true,
       createdAt: true,
       populate: {
         owner: {
           name: true
         }
       }
     }
  })
});
```

**Comment by gyzerok** [comment]
@pcwinters btw may we could contact somehow to have a real-time discussion?

**Comment by pcwinters** [comment]
@gyzerok :+1: 
I think this pull request unlocks the potential you're describing, but it doesn't make an attempt to implement it. Our use case at Bronto Software is wildly incompatible with a vanilla REST or GraphQL solution, so we've implemented our own Adaptor. By utilizing a 'query' function, you can build an adaptor that does *whatever* you want. Buyer beware.

**Comment by gyzerok** [comment]
@pcwinters Yeah, I've get it now. Then there is an idea to stabilize your API approach and keep working on the core to make it stable as well and introduce some new features.

**Comment by pcwinters** [comment]
@gyzerok, I've merged with master, updated some tests and eslint stuffs. This is good to go! Please take a look.

**Comment by pdillon** [comment]
:+1:

**Comment by gyzerok** [comment]
@pcwinters thanks! Let me take a few days to deal with it.

**Comment by gyzerok** [comment]
@pcwinters What do you think would be better: discuss some things before merge or merge this, create separate branch for next release and discuss inside its PR?

**Pull request merged**
