### PR TITLE
Adding decorator example

### PR DESCRIPTION
**Pull request by anaibol**
#100

### CODE REVIEW

**Comment by gyzerok** [comment]
Thanks for your PR. 

What do you think about moving it closer to the API, adding notion about both `container` and `presenter` and removing link to decorator legacy stuff?

**Comment by anaibol** [comment]
Well, I am not sure about removing the decorator legacy plugin stuff, because Babel doesn't have support currently. See: http://babeljs.io/docs/plugins/transform-decorators/

**Comment by gyzerok** [comment]
@anaibol this project isn't connected with babel. So if one need to know how to add decorators transpilation he should go to the babel docs, not to this ones. One the other hand I don't think it is good idea to follow this stuff and update readme every time it changes.

**Comment by anaibol** [comment]
As you wish, in my case I would have liked to find an example with decorators when I found this repo.

**Comment by gyzerok** [comment]
Anyway I think it would be better without lagcy link. I'd be happy to merge your PR as soon as you'd remove it :)

**Comment by anaibol** [comment]
Done!

**Comment by gyzerok** [comment]
Great! Thank you

**Pull request merged**
